// src/containers/skills/index.tsx
import React, { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ListIcon, ListIconModel, Types } from '../../shared/icons';

export const ListSkills = `
  display: grid;
  row-gap: 0.625rem;
  grid-template-columns: repeat(5, minmax(0, 1fr));

  @media (min-width: 600px) {
    margin-left: 0;
    margin-right: 0;
    gap: 0.938rem;
    row-gap: 1.25rem;
    grid-template-columns: repeat(6, minmax(0, 1fr));
  }

  @media (min-width: 640px) {
    margin-left: 0;
    margin-right: 0;
    row-gap: 1.25rem;
    grid-template-columns: repeat(7, minmax(0, 1fr));
  }

  @media (min-width: 768px) {
    grid-template-columns: repeat(8, minmax(0, 1fr));
  }

  @media (min-width: 912px) {
    grid-template-columns: repeat(9, minmax(0, 1fr));
  }

  @media (min-width: 1024px) {
    min-height: 21.875rem;
    grid-template-columns: repeat(10, minmax(0, 1fr)) !important;
  }
`;

export default function Skills() {
  const [filteredIcons, setFilteredIcons] = useState<ListIconModel[]>(ListIcon);
  const [currentTag, setCurrentTag] = useState<Types>(Types.ALL);

  const onFilter = (tag: Types) => {
    switch (tag) {
      case Types.ALL:
        setFilteredIcons(ListIcon);
        break;
      case Types.FRONT_END:
      case Types.BACK_END:
      case Types.DATABASE:
      case Types.OTHERS:
        const filtered = ListIcon.filter((item) => item.type.includes(tag));
        setFilteredIcons(filtered);
        break;
    }
  };

  return (
    <section id="skills" className="bg-[rgba(147,107,232,0.15)]">
      <div className="max-w-[72.813rem] px-2.5 mx-auto sm:px-5 md:px-7.5">
        <div className="h-full shrink-0 flex flex-col items-center justify-center py-[3.125rem] lg:py-[6.25rem]">
          <ul
            className="flex w-full flex-row items-center justify-start gap-2 overflow-x-scroll overflow-y-hidden scroll-snap-x snap-mandatory scrollbar-none pt-2 pb-8 list-none select-none  
          sm:justify-center sm:overflow-x-hidden sm:gap-[0.625rem] sm:pb-[2rem]"
          >
            {Object.values(Types).map((item: Types, i: number) => (
              <li
                key={i}
                onClick={() => {
                  onFilter(item);
                  setCurrentTag(item);
                }}
                data-text={item}
                className={`px-4 py-1 mx-1 text-base font-medium leading-5 border rounded-[0.7rem] transition-colors duration-200 relative cursor-pointer after:content-[attr(data-text)] after:block after:whitespace-nowrap ${
                  item === currentTag ? 'text-white bg-primary border-white' : 'text-gray-600 border-gray-600 hover:text-white hover:bg-primary hover:border-white'
                }`}
              ></li>
            ))}
          </ul>
          <div className="w-full flex flex-col flex-wrap text-center min-h-[21.875rem]">
            <motion.div
              className="
                    grid grid-cols-4 gap-[0.625rem]

                    [@media(min-width:600px)]:ml-0 
                    [@media(min-width:600px)]:mr-0 
                    [@media(min-width:600px)]:gap-[0.938rem] 
                    [@media(min-width:600px)]:gap-[1.25rem] 
                    [@media(min-width:600px)]:grid-cols-6

                    sm:ml-0 
                    sm:mr-0 
                    sm:gap-[1.25rem] 
                    sm:grid-cols-7

                    md:grid-cols-8

                    [@media(min-width:912px)]:grid-cols-9

                    lt:min-h-[21.875rem]  lt:grid-cols-[repeat(13,minmax(0,1fr))]
              "
            >
              <AnimatePresence>
                {filteredIcons
                  .filter((item) => item.active)
                  .map((icon, index) => (
                    <React.Fragment key={index}>
                      <motion.div
                        layout
                        animate={{ opacity: 1 }}
                        initial={{ opacity: 0 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.5 }}
                        whileHover={{ scale: 1.15 }}
                        whileTap={{ scale: 0.9 }}
                        className="flex flex-col items-center justify-center bg-white rounded-[12px] w-[80px] h-[80px] gap-[0.313rem]rounded-[16px]"
                      >
                        <div className="flex items-center justify-center shrink-0 fill-[rgba(255, 255, 255, 0.1)]">
                          <div className="w-full h-full" role="tooltip">
                            <img src={icon.path} alt={icon.name} width="100%" height="100%" />
                          </div>
                        </div>
                      </motion.div>

                      {/* Chèn SkillEmpty giữa các phần tử, không chèn sau phần tử cuối */}
                      {index < filteredIcons.length - 1 && (
                        <motion.div className="flex flex-col items-center justify-center bg-[rgba(255, 255, 255, 0.75)] border-[3px] border-dashed border-[#cccc] rounded-[16px] w-[80px] h-[80px] gap-[0.313rem]">
                          <div className="flex items-center justify-center shrink-0 fill-[rgba(255, 255, 255, 0.1)]">
                            <div className="w-0 h-0" />
                          </div>
                        </motion.div>
                      )}
                    </React.Fragment>
                  ))}
              </AnimatePresence>
            </motion.div>
          </div>
        </div>
      </div>
    </section>
  );
}

// app/components/section/Skills.vue
<script setup lang="ts">
import type { Skill } from '~/types'

// Skills are fetched from /api/skills, then filtered by category on the client.
// - Framer <AnimatePresence>+layout -> <TransitionGroup name="skill"> (fade + FLIP move,
//   CSS in index.scss). whileHover/whileTap -> v-motion :hovered/:tapped.
const { data: skills } = await useSkills()

const tags: string[] = ['All', 'Front end', 'Back end', 'Database', 'Others']
const currentTag = ref<string>('All')

const filtered = computed<Skill[]>(() =>
	currentTag.value === 'All'
		? skills.value
		: skills.value.filter((item) => item.type.includes(currentTag.value))
)

const onFilter = (tag: string) => {
	currentTag.value = tag
}

// Flatten to a single keyed list (icon card + trailing dashed divider, interleaved).
// The divider count keys off the full filtered length, identical to the original index
// comparison `index < filteredIcons.length - 1`.
type Cell =
	| { key: string; kind: 'icon'; icon: Skill }
	| { key: string; kind: 'divider' }

const cells = computed<Cell[]>(() => {
	const active = filtered.value.filter((item) => item.active)
	const total = filtered.value.length
	const out: Cell[] = []
	active.forEach((icon, index) => {
		out.push({ key: `icon-${icon.name}`, kind: 'icon', icon })
		if (index < total - 1) out.push({ key: `divider-${icon.name}`, kind: 'divider' })
	})
	return out
})

const cardClass =
	'flex flex-col items-center justify-center bg-surface rounded-[12px] group w-[80px] h-[80px] gap-[5px]rounded-[16px] shadow-[0px_10px_10px_0px_rgba(31,13,64,0.10),_0px_0px_2px_0px_rgba(31,13,64,0.08)]'
const dividerClass =
	'flex flex-col items-center justify-center bg-[rgba(255,255,255,0.75)] w-[80px] min-w-[80px] max-w-[80px] h-[80px] gap-[5px] border-[3px] border-dashed border-line-dashed rounded-[16px]'
</script>

<template>
	<section id="skills" class="bg-surface-alt">
		<div class="max-w-[1165px] px-[10px] mx-auto sm:px-[20px] md:px-[30px]">
			<div
				class="h-full shrink-0 flex flex-col items-center justify-center py-[50px] lg:py-[100px]">
				<ul
					class="flex w-full flex-row items-center justify-start gap-[8px] overflow-x-scroll overflow-y-hidden scroll-snap-x snap-mandatory scrollbar-none pt-[15px] pb-[32px] list-none select-none sm:justify-center sm:overflow-x-hidden sm:gap-[10px] sm:pb-[32px]">
					<li
						v-for="(item, i) in tags"
						:key="i"
						class="px-[20px] py-[4px] mx-[4px] relative overflow-hidden bg-surface transition-all rounded-[11px] text-base font-medium leading-5 border border-primary before:absolute before:bottom-0 before:left-0 before:top-0 before:z-0 before:h-full before:w-0 before:bg-primary before:transition-all before:duration-500 hover:text-white hover:before:bg-primary hover:shadow-primary hover:before:left-0 hover:before:w-full hover:shadow-2xl"
						:class="
							item === currentTag
								? 'text-white before:bg-primary shadow-primary before:left-0 before:w-full shadow-2xl'
								: 'text-primary'
						"
						@click="onFilter(item)">
						<span class="relative z-10" :style="{ backfaceVisibility: 'hidden' }">{{ item }}</span>
					</li>
				</ul>

				<div class="w-full flex flex-col flex-wrap text-center min-h-[350px]">
					<TransitionGroup
						tag="div"
						name="skill"
						:style="{ display: 'grid' }"
						class="grid-cols-4 gap-[10px] [@media(min-width:600px)]:ml-0 [@media(min-width:600px)]:mr-0 [@media(min-width:600px)]:gap-[15px] [@media(min-width:600px)]:gap-[20px] [@media(min-width:600px)]:grid-cols-6 sm:ml-0 sm:mr-0 sm:gap-[20px] sm:grid-cols-7 md:grid-cols-8 [@media(min-width:912px)]:grid-cols-9 lt:min-h-[350px] lt:grid-cols-[repeat(13,minmax(0,1fr))]">
						<div
							v-for="cell in cells"
							:key="cell.key"
							v-motion
							:hovered="cell.kind === 'icon' ? { scale: 1.15 } : {}"
							:tapped="cell.kind === 'icon' ? { scale: 0.9 } : {}"
							:class="cell.kind === 'icon' ? cardClass : dividerClass">
							<template v-if="cell.kind === 'icon'">
								<div
									class="flex items-center justify-center shrink-0 fill-[rgba(255,255,255,0.1)]">
									<div class="relative w-[55px] h-[55px] cursor-pointer">
										<div
											class="absolute inset-0 opacity-100 group-hover:opacity-0 transition-opacity duration-300">
											<img
												:src="`${cell.icon.path}/grey.svg`"
												:alt="cell.icon.name"
												width="100%"
												height="100%" />
										</div>
										<div
											class="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
											<img
												:src="`${cell.icon.path}/default.svg`"
												:alt="cell.icon.name"
												width="100%"
												height="100%" />
										</div>
									</div>
								</div>
							</template>
							<template v-else>
								<div
									class="flex items-center justify-center shrink-0 fill-[rgba(255,255,255,0.1)]">
									<div class="w-0 h-0" />
								</div>
							</template>
						</div>
					</TransitionGroup>
				</div>
			</div>
		</div>
	</section>
</template>
